<?php

declare(strict_types=1);

namespace Naf\Board\Support;

use function Naf\I18n\t;

/** Request-language messages used by the browser modules. @internal */
final class BrowserWords
{
    private const array KEYS = [
        ': ausgeführt.',
        ':email · bestätigt',
        ':email · nicht bestätigt',
        ':mode · :count von :total Werkzeugen',
        ':tool – ausführen?',
        'AI-Einstellungen gespeichert.',
        'Ablehnen',
        'Aktuellen Stand laden',
        'Antwort gestoppt. Bereits bestätigte Änderungen bleiben erhalten.',
        'Antwort kopiert.',
        'Antwort prüfen',
        'Aufzählung',
        'Beschreibe das Ziel und die nächsten Schritte …',
        'Benachrichtigungen aktiv',
        'Beschreibung bearbeiten',
        'Bestätigung offen für :email',
        'Bitte aktuellen Stand laden',
        'Bitte lade und wähle zuerst ein Chat-Modell.',
        'Bitte melde dich erneut an oder lade die Seite neu.',
        'Bitte melde dich erneut an.',
        'Bitte prüfe den eingegebenen Wert.',
        'Bitte prüfe die vorgeschlagene Änderung.',
        'Bitte verwende eine lokale Ollama-Adresse ohne Zugangsdaten oder Pfad.',
        'Bitte warte, bis das Speichern abgeschlossen ist.',
        'Bitte wähle zuerst ein Chat-Modell.',
        'Codeblock',
        'Das Modell hat ein nicht verfügbares Werkzeug angefragt.',
        'Das Modell hat eine leere Antwort geliefert. Versuche es erneut.',
        'Das Modul stellt kein mount(root, context, api) bereit.',
        'Das Ticket wurde inzwischen geändert. Bitte lade den aktuellen Stand.',
        'Denkt nach …',
        'Der Bearbeitungszustand hat sich geändert. Bitte lade das Ticket neu.',
        'Der Browserspeicher ist voll oder gesperrt. Bitte exportiere oder lösche ältere Chats.',
        'Der Texteditor ist noch nicht bereit.',
        'Der Texteditor konnte nicht geladen werden. Bitte erneut versuchen.',
        'Die Anfrage konnte nicht verarbeitet werden. Bitte lade die Seite neu.',
        'Die Datei ist :size groß. Erlaubt sind 10 MiB.',
        'Die Datei konnte nicht angehängt werden.',
        'Die Helligkeit konnte nicht gespeichert werden.',
        'Die Verbindung ist unterbrochen. Bitte lade das Board neu.',
        'Die Verbindung ist unterbrochen. Deine Eingaben bleiben erhalten.',
        'Die Verbindung wurde unterbrochen. Bitte versuche es erneut.',
        'Die Zeiterfassung ließ sich nicht ändern.',
        'Die maximale Anzahl an Werkzeugschritten ist erreicht. Stelle eine gezieltere Frage.',
        'Die vorgeschlagene Änderung wurde nicht ausgeführt.',
        'Die Änderung konnte nicht gespeichert werden.',
        'Dieser Beitrag konnte nicht geladen werden: :reason',
        'Dieses Modell unterstützt keine Werkzeuge. Bitte wähle ein anderes Modell.',
        'Durchgestrichen',
        'Embedding-Auswahl nicht verfügbar; begrenzte Stichwortsuche aktiv.',
        'Embedding-Modell nicht installiert.',
        'Es ist noch kein Feedback vorhanden.',
        'Feedback gespeichert',
        'Fett',
        'Formatierung entfernen',
        'Gespeichert',
        'Gespeichert · Bitte neu laden',
        'Gespeichert. Der aktuelle Stand konnte nicht geladen werden. Bitte lade die Seite neu.',
        'Index: :cached wiederverwendet, :new neu berechnet.',
        'Kein Modell gewählt',
        'Kein Modell mit Werkzeugunterstützung gefunden',
        'Kein passendes Werkzeug gefunden.',
        'Keine ungespeicherten Änderungen',
        'Kopieren ist in diesem Browser nicht verfügbar.',
        'Kursiv',
        'Leerer Embedding-Vektor.',
        'Löschen',
        'Modelle werden geprüft …',
        'Nafinity AI ist nicht erreichbar. Läuft Ollama noch?',
        'Neues Ticket',
        'Nicht gespeichert',
        'Nicht gespeichert · Bitte aktuellen Stand laden',
        'Nummerierte Liste',
        'Nur begrenzte Stichwortsuche',
        'Ollama hat ungültige Streaming-Daten geliefert.',
        'Semantische Auswahl',
        'Speichern fehlgeschlagen.',
        'Stichwortauswahl',
        'Stummgeschaltet',
        'Ticket erstellt',
        'Ticket erstellt. Bitte öffne den gespeicherten Stand.',
        'Ticket konnte nicht geladen werden.',
        'Ticket wird geladen …',
        'Ticketdetails',
        'Ungültige Embedding-Dimensionen.',
        'Ungültige Embedding-Werte.',
        'Unterstrichen',
        'Unvollständige Embedding-Antwort.',
        'Verbinde mit dem lokalen Modell …',
        'Verbindung unterbrochen. Bitte prüfe den aktuellen Stand vor einem erneuten Versuch.',
        'Verschieben fehlgeschlagen.',
        'Vorschlag übernommen. Speichere die AI-Einstellungen, um das Gedächtnis zu aktualisieren.',
        'Weitere Änderungen ausstehend …',
        'Werkzeugindex: :count von :total bereit …',
        'Wird gespeichert …',
        'Wähle ein Modell und speichere deine Einstellungen.',
        'Wähle zuerst ein Modell in den AI-Einstellungen.',
        'Zitat',
        'Änderung abgelehnt.',
        'Änderung bestätigen',
        'Änderungen werden gespeichert …',
        'Überschrift oder Fließtext',
    ];

    public static function all(): array
    {
        return array_combine(self::KEYS, array_map(t(...), self::KEYS));
    }
}
